### ISSUE TITLE
1.0.3b Sim deletion error

### ISSUE THREAD

**Issue by Gareld-Michael** [ashjack/Sim-U-Kraft-Reloaded#62]
I actually noticed this by accident, but when you start a new game and even accidentally click not to run Sim-U-Kraft it refuses to run it on other worlds also; It also deletes older sims that were on other worlds when you play them and others will not come. However, strangely enough, you can still see that they are living in their homes and you can still see their names there.

**Comment by Gareld-Michael** [comment]
If you already fixed that in a new version like 1.0.4a that's good but either way I think I'll try 1.0.4 to see if it works. thanks for listening.

**Comment by Gareld-Michael** [comment]
I didn't realize this till after I read your notice in how to properly install SUK I now realize that this may have happened because I had the resources folder in the mods folder not a step up. Sorry, but I would recommend testing it for that error if it really is there. Thx

**Comment by ashjack** [comment]
Hi, the bug you have described here is known as the infamous 'world merge bug'

This bug has been around since Satscape developed the mod, and I am still trying to fix it. If you play multiple worlds in the same session of Minecraft with Sim-U-Kraft Reloaded installed, the data from Sim-U-Kraft merges. Sims change, and as you have mentioned, so do gamemodes. Currently, the only way around this is to reload Minecraft whenever you want to load a different world. I know it's not ideal, and I wish there was a better way, but I still am unable to find the cause, so it'll have to do now. Sorry for the problem it has caused you.
